### ISSUE TITLE
Red dragon removes transcoder

### ISSUE THREAD

**Issue by everamzah** [duane-r/fun_caves#32]
This is more of a transcoder issue, again.  If one of the pair is removed, but not dug - in this case a red dragon firebombed it - the originating transcoder still teleports.  If one of them tries to go to another that isn't there, it seems like it should fail.

**Comment by duane-r** [comment]
There's not much I can do about that since I can't know if either of them still exists when someone decides to teleport.

**Comment by everamzah** [comment]
It would be funny, then, to inform the program that the pair is broken upon arriving, and remove the originator!

I'll again close this as a mob issue.

**Comment by duane-r** [comment]
>It would be funny, then, to inform the program that the pair is broken upon arriving, and remove the originator!

That would have to be done as an after() call, and since the system is going to try to unload those blocks when you leave, you're not guaranteed access to them.

It would be a lot better to make the translocators indestructible. Unfortunately, the mobs explosion function doesn't check for protection properly. If the dragon is aiming right at them, the explosion is stifled; if it aims below them, they're consumed by fire, regardless of protection.

**Comment by duane-r** [comment]
I put in a pull request to fix the explosion issue, and it seems to make it impossible for the dragon to harm a translocator. Of course, it might end up floating out of reach, but that's a minor issue.

https://github.com/tenplus1/mobs_redo/pull/11/files
