### ISSUE TITLE
Transcoders breaking if server unexpectedly shuts down

### ISSUE THREAD

**Issue by everamzah** [duane-r/fun_caves#33]
I had a crash (on_die() in elixir.lua line 34, attempt to index a nil value) and when I restarted the server, the transcoders no longer worked.  I believe they're persisting fine between regular restarts (where `register_on_shutdown()` takes place) but not on crashes (where `register_on_shutdown() doesn't get called).  Will continue to test and report.

**Comment by duane-r** [comment]
Ok, I spotted the problem -- it was a stupid syntax error. Unfortunately, the translocators that got lost are going to cause problems with the new ones since they both have the same legitimate numbers. You'll have to remove them all then start creating new ones (or manually enter coordinates in the db file). Without some way to find them all in the world data, I can't make it any neater than that.

**Comment by everamzah** [comment]
Oh that's fine, I don't care about an old world.  That's what new worlds are for.  Heh.  I really like the transcoders!  Especially since they're so quick.  I'll close this for now, and observe their behavior - the new ones - when the server crashes again.
